name: DEHPlugin
version: 0.1.5
main: net.rishy.dehplugin.DEHPlugin
description: A plugin for the SOC production of Dear Evan Hansen
author: R1shy
website: https://papermc.io
api-version: '1.21.11'
dependencies:
  server:
    WorldEdit:
      load: BEFORE
      required: true
